[build]
  publish = "public/dist"
  command = "npm run build"

[[redirects]]
  from = "/bee.js"
  to = "https://cdn.splitbee.io/sb.js"
  status = 200

[[redirects]]
  from = "/_hive/*"
  to = "https://hive.splitbee.io/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200